{
  "version": 1,
  "syncMode": 1,
  "gapBehavior": 1,
  "canvas": {
    "width": 1920,
    "height": 1080,
    "defaultFit": "fit-height"
  },
  "tracks": [
    {
      "id": "11111111-1111-1111-1111-111111111111",
      "filePath": "test_1080p60.mp4",
      "name": "Substitute_A",
      "mediaIn": "00:00:00",
      "mediaOut": null,
      "timelineOffset": "00:00:10",
      "mediaDuration": "00:00:30",
      "syncOffset": "00:00:00",
      "frameRate": 60,
      "isEnabled": true
    },
    {
      "id": "22222222-2222-2222-2222-222222222222",
      "filePath": "test_720p25.mkv",
      "name": "Substitute_B",
      "mediaIn": "00:00:02",
      "mediaOut": null,
      "timelineOffset": "00:00:50",
      "mediaDuration": "00:00:20",
      "syncOffset": "00:00:00.5000000",
      "frameRate": 25,
      "isEnabled": true
    },
    {
      "id": "33333333-3333-3333-3333-333333333333",
      "filePath": "test_720p25.avi",
      "name": "Substitute_D_disabled",
      "mediaIn": "00:00:00",
      "mediaOut": null,
      "timelineOffset": "00:01:16",
      "mediaDuration": "00:00:20",
      "syncOffset": "00:00:00",
      "frameRate": 25,
      "isEnabled": false
    },
    {
      "id": "44444444-4444-4444-4444-444444444444",
      "filePath": "test_1080p60.mp4",
      "name": "Substitute_C",
      "mediaIn": "00:00:00",
      "mediaOut": null,
      "timelineOffset": "00:01:16",
      "mediaDuration": "00:00:30",
      "syncOffset": "00:00:00",
      "frameRate": 60,
      "isEnabled": true
    }
  ]
}