namespace TimecodeSyncPlayer.Tests.LatchLifetime;

/// <summary>
/// v0.5.2 段 0: ラッチの寿命の表（特性テストのデータ）。行 = ラッチ × できごと。
/// 現状 = 今のコードでできごとの直後にラッチが立っているか（テストで確かめる）。
/// 意図 = 設計書 §6 の候補の行は Clear（現状と食い違う行が §6 の候補そのもの）、できごとのコードが
/// 明示的に消している行は Clear（現状と同じ向き）、それ以外は Undecided。
/// 根拠の行番号は v0.5.2 段 0 の時点のファイル。人間向けの写しは docs/design/v0.5.2-latch-table.md。
/// 段 1・2 の間はこの表を変えない（段 3 で §6 の候補を直すとき、その行の現状の列だけを書き換える）。
/// </summary>
public static class LatchLifetimeTable
{
    private const CurrentBehavior Clears = CurrentBehavior.Clears;
    private const CurrentBehavior Keeps = CurrentBehavior.Keeps;
    private const CurrentBehavior NotApplicable = CurrentBehavior.NotApplicable;
    private const LatchIntent Clear = LatchIntent.Clear;
    private const LatchIntent Keep = LatchIntent.Keep;
    private const LatchIntent Undecided = LatchIntent.Undecided;

    public static IReadOnlyList<LatchLifetimeRow> Rows { get; } =
    [
        // ── LtcSyncController.heldReapplyDone ──
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.FileLoad, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（TimecodeSyncService.BeginFileLoad の FileLoad を LifecycleRaised で受け、LtcSyncController が 2 つのラッチを下ろす。TimecodeSyncService.cs:68）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 5: v0.5.3 では直さない（ギャップの読み込みは Jump の適用の途中で起きる（GapEnterCoordinator.cs:213・:256）。設計 `v0.5.3-gap-load-entry.md` の親の承認）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の SyncModeChanged で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SyncEnabledOn, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の SyncEnabled で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:387, :422 監視の停止で下ろす"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:387, :422）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.ManualSeek, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の ManualSeek（と TimelineSeek）で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:582 ギャップへ入るフレームは Normal で、値が進むフレームとして下ろす"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入る Normal フレームで下ろす（LtcSyncController.cs:582）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:582 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.JumpRecovery, Clears, Undecided,
            "v0.5.4 B7: Jump は次の 1 フレームで確かめてから ApplyConfirmedJump で適用し、そこでこのラッチを下ろす（LtcSyncController.cs:747）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:582 Normal フレームで下ろす（:97-100 のコメント: Normal/Initial で解除）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.pendingJump ──
        new(LatchArrangements.PendingJump, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:194 モード切替で未確認の Jump を捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は未確認の Jump に触れない（捨てるのは :194・:257・:372・:384・:419・:458）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は未確認の Jump に触れない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:384, :419 監視の停止で捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で捨てる（LtcSyncController.cs:384, :419）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.ManualSeek, Clears, Clear,
            "LtcSyncController.cs:257 CancelPendingSync が捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:456-458 次のフレームで必ず下ろす（確認できなければ捨てる）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで下ろす（LtcSyncController.cs:458）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:458 前提の無音の後の最初の有効フレームで下ろす"),
        new(LatchArrangements.PendingJump, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: 前提の保持フレームで下ろす（LtcSyncController.cs:458）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:458 次のフレームで下ろす（+1 フレームでないので確認にならず捨てる :462-479）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.FpsModeChanged, Clears, Clear,
            "LtcSyncController.cs:372 fps モードの変更で捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.pendingSync ──
        new(LatchArrangements.PendingSync, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.PendingSync, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:199 の再適用が :213 で下ろすが、v0.5.4 段 B3 の配置（直前にシークが失敗し続けた）では 1 サンプル目が D37-a の安定ゲートで保留され、保留は次の有効フレームまで残る（SyncDecisionEngine.cs: ゲートの保留）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:186 の再適用が :213 で下ろし、同期無効で :216 で戻る"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で下ろす（LtcSyncController.cs:186 → :213）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:383, :418 監視の停止で下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:383, :418）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.ManualSeek, Clears, Clear,
            "LtcSyncController.cs:256 CancelPendingSync が下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset は保留の同期要求に触れない（下ろすのは :213・:256・:325・:383・:418・:947）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:947 有効フレームで下ろし、ギャップの同期要求は Complete（:1199 → :325）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで下ろす（LtcSyncController.cs:947）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SignalRecovered, NotApplicable, Undecided,
            "前提で消える: 前提の無音の Tick が保留を再送し（LtcSyncController.cs:956-963）、Complete で :325 が下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: 前提の Tick が保留を再送し（LtcSyncController.cs:956-963）、Complete で :325 が下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:947 有効フレームで下ろし、同期要求は Complete（:325）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PendingSync, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.lastHeldEffective ──
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:381, :416 監視の停止で下ろす"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:381, :416）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:584 ギャップへ入るフレームは Normal で、保持が明けたとして下ろす"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入る Normal フレームで下ろす（LtcSyncController.cs:584）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:584 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.JumpRecovery, Clears, Clear,
            "v0.5.3 段 3k で下ろすようにした（損失中の Jump の即時復帰で _input.ClearHeldEffective を呼ぶ。LtcSyncController.cs:637）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:584 値が進むフレームで下ろす（:89-94 のコメント）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.heldLossLanding ──
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:382, :417 監視の停止で下ろす"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:382, :417）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:585 ギャップへ入るフレームは Normal で、保持が明けたとして下ろす"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: 停止モードの損失で一時停止中は同期を抑止し（LtcSyncController.cs:1127）、ギャップへ入れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:585 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.JumpRecovery, Clears, Clear,
            "v0.5.3 段 3k で下ろすようにした（損失中の Jump の即時復帰で _input.ClearHeldLossLanding を呼ぶ。LtcSyncController.cs:636）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.NormalFrame, Keeps, Keep,
            "LtcSyncController.cs:705 v0.6.1（3-5 節の (iii)）: 保持の損失の後の +1 フレームは這う前進で、保持を切らない（値が 1 歩進むだけでは保持は明けない。以前は Normal として下ろしていた）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.lastAppliedLtc ──
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:380, :415 監視の停止で下ろす"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:380, :415）"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:600 復帰した Jump の値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.lastAcceptedLtc ──
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:379, :414 監視の停止で下ろす"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:379, :414）"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:597 復帰した Jump の値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.rateRestorePending ──
        new(LatchArrangements.RateRestorePending, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:191 の ResetCorrection は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "v0.5.4 K5 で直した（根拠: LtcSyncController.cs:238 の SyncDisabled が RetryRateRestoreIfPending で復帰待ちを再試行する。§6 の 7）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化（LtcSyncController.cs:238 の RetryRateRestoreIfPending）が復帰待ちを再試行して下ろす（v0.5.4 K5、§6 の 7）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:260 の ResetCorrection は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1176 の ResetCorrection は :292 で何もしない。ギャップで一時停止し、復帰（:784-791）は :776 で届かない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.GapExit, Clears, Clear,
            "v0.5.4 B6b（追補 5、TSP-Fable の判定）: ギャップの出口の relocate の発行（ContinueOnTrackCoordinator.cs:56 ReportSeekSent → LtcSyncController.cs:379-389 OnSeekIssued）で下ろす。規則 3: relocate は varispeed を持ち越さない（全経路で同じ）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:784-791 補正評価の前に 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSyncController.cs:610 → :784-791 補正評価の前に 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:615 → :784-791 補正評価の前に 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.smoothUnavailable ──
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.FileLoad, Clears, Clear,
            "v0.5.4 K5 で直した（根拠: LtcSyncController.cs:125 の FileLoad で _rate.ResetSmoothAvailability を呼ぶ。§6 の 6）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 6: K5 は Single の読み込み（FileLoad）だけを直した。ギャップの読み込み（GapFreezeLoad）は Jump の適用の途中で起きる（GapEnterCoordinator.cs:213・:256）Continue の経路のため対象外（v0.5.3 の設計 `v0.5.3-gap-load-entry.md` の親の承認を維持）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:192 モード切替で Smooth を再試行できるようにする"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:173 同期の切替で Smooth を再試行できるようにする"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で下ろす（LtcSyncController.cs:173）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.ManualSeek, Clears, Clear,
            "利用者決定 2026-09-25（§7）: v0.5.3 で直す。v0.5.3 段 3h で下ろすようにした（LtcSyncController.OnLifecycle の ManualSeek（と TimelineSeek）で _rate.ResetSmoothAvailability を呼ぶ。LtcSyncController.cs:237）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 → :286-298 ResetCorrection は :81 の _smoothAvailable を戻さない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.correctionPausedForPosition ──
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.FileLoad, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす。再適用（:199）の同期要求は補正評価（ApplyCorrection）を呼ばない（:300-332）"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす。再適用（:186）の同期要求は補正評価（ApplyCorrection）を呼ばない（:300-332）"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす。ギャップで一時停止し、補正評価は :776 で戻って届かない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.GapExit, Clears, Clear,
            "v0.5.4 B6b（追補 5、TSP-Fable の判定）: ギャップの出口の relocate の発行（ContinueOnTrackCoordinator.cs:56 ReportSeekSent → LtcSyncController.cs:379-389 OnSeekIssued）で下ろす。規則 3: relocate は varispeed を持ち越さない（全経路で同じ）"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:615 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSyncController.cs:610 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:615 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.rateNotUnity ──
        new(LatchArrangements.RateNotUnity, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:191 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:172 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で 1.0 に戻す（LtcSyncController.cs:172 → :294-295）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "利用者決定 2026-09-25（§7）: v0.5.3 で直す。v0.5.3 段 3h で下ろすようにした（LtcSyncController.OnLifecycle の MonitoringStopped と MonitorDeviceStopped で ResetCorrection を呼ぶ。LtcSyncController.cs:263）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で 1.0 に戻す（LtcSyncController.cs:263, :274 の ResetCorrection）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.ManualSeek, Clears, Clear,
            "LtcSyncController.cs:260 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.StopPlayback, Clears, Clear,
            "MainWindow.xaml.cs:1536 → LtcSyncController.cs:280 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:1176 → :294-295 ギャップでは倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで 1.0 に戻す（LtcSyncController.cs:1176）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:859-878 補正評価は残差（0.2 秒）に応じて Smooth の倍率を掛け続ける"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:859-878 補正評価は残差（0.2 秒）に応じて Smooth の倍率を掛け続ける"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:859-878 補正評価は残差（0.2 秒）に応じて Smooth の倍率を掛け続ける"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.CorrectionModeChanged, Clears, Clear,
            "v0.5.3 段 3h で下ろすようにした（LtcSyncController.OnLifecycle の CorrectionModeChanged で ResetCorrection を呼ぶ。LtcSyncController.cs:242）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.loadingFile ──
        new(LatchArrangements.LoadingFile, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:433 読み込みで立て直す"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SyncModeChanged, Clears, Undecided,
            "v0.5.4 段 B3: ClearSeekState は読み込み中なら着地待ちを残し（TimecodeSyncService.cs: ClearSeekState）、再適用の評価が最初のフレームの配信を観測して解除する（TimecodeSyncService.cs: ObserveLandingState の TryReleaseFileLoadAfterLanding）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "v0.5.3 段 3d で取り消すようにした（TimecodeSyncService.OnLifecycle の SyncDisabled でロード中の印と解除の回収待ちを下ろす。解除はしない（着地窓を開かない）。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で取り消す（v0.5.3 段 3d。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.StopPlayback, Clears, Clear,
            "v0.5.3 段 3d で取り消すようにした（LtcSyncController.PlaybackStopped から _syncService.OnLifecycle(PlaybackStopped) を呼ぶ。解除はしない。LtcSyncController.cs:343）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は読み込みの解除（TimecodeSyncService.cs:457-479）を通らない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:49-58 同じトラックへのギャップ明けは読み込まず、解除の判定（:119）も通らない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SignalRecovered, NotApplicable, Undecided,
            "前提で消える: v0.5.4 段 B3 でロードの成立は着地の事象になった。前提の無音 Tick の観測で読み込みを解除する（TimecodeSyncService.cs: ObserveLandingState の TryReleaseFileLoadAfterLanding）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: v0.5.4 段 B3 でロードの成立は着地の事象になった。前提の保持（Duplicate）の観測で読み込みを解除する（TimecodeSyncService.cs: ObserveLandingState の TryReleaseFileLoadAfterLanding）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.NormalFrame, Clears, Undecided,
            "v0.5.4 段 B3: 有効フレームの着地の観測で読み込みを解除する（TimecodeSyncService.cs: ObserveLandingState の TryReleaseFileLoadAfterLanding）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.fileLoadReleasePending ──
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.FileLoad, Clears, Clear,
            "TimecodeSyncService.cs:434 読み込みで下ろす"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.FileLoadWithoutBegin, Clears, Clear,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad が解除の回収待ちを下ろす）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SyncEnabledOff, Clears, Undecided,
            "v0.5.3 段 3d で取り消すようにした（TimecodeSyncService.OnLifecycle の SyncDisabled で解除の回収待ちも下ろす。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で取り消す（v0.5.3 段 3d。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.StopPlayback, Clears, Undecided,
            "v0.5.3 段 3d で取り消すようにした（LtcSyncController.PlaybackStopped から _syncService.OnLifecycle(PlaybackStopped) を呼び、解除の回収待ちも下ろす。LtcSyncController.cs:343）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.GapEnter, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.GapExit, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SignalRecovered, Clears, Undecided,
            "LtcSyncController.cs:830 v0.6.1: 無音の後の 1 枚目は這う前進（3-5 の (iii)）で、保持の枝の読み込みの解除の再適用（TryReapplyAfterFileLoadRelease）が回収待ちを回収して下ろす（以前は Normal として回収を通らなかった）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: 前提の保持フレーム（LtcSyncController.cs:573-576 → :738-763）が PollFileLoadRelease で回収して下ろす（TimecodeSyncService.cs:520-523）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.positionUntrusted ──
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.FileLoad, Keeps, Undecided,
            "v0.5.4 段 B3: BeginFileLoad が読み込みの世代の着地待ちに入る（TimecodeSyncService.cs: BeginFileLoad → BeginLoadWait。位置は着地まで使わない）"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 2: PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginFileLoad（TimecodeSyncService.cs:446）を通らない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:196 → TimecodeSyncService.cs:501 保留を捨てて位置を使い直す"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:176 → TimecodeSyncService.cs:501 保留を捨てて位置を使い直す"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で信頼し直す（LtcSyncController.cs:176 → TimecodeSyncService.cs:501）"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 は TimecodeSyncService に触れない。シークバーは ClearSeekState を呼ばない（MainWindow.xaml.cs:1977, :2642。呼ぶのはタイムラインのシーク :1966-1967）"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は同期評価（EvaluateDecision）も読み込みの解除も通らない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:51 ギャップ明けのシークはプレイヤーへ直接出し、保留の決着（TimecodeSyncService.cs:582-597）を通らない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "着地の冷却中（TimecodeSyncSeekState.cs:83-87）は保留のままで、信頼を戻す決着（TimecodeSyncService.cs:582-597）に届かない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "着地の冷却中（TimecodeSyncSeekState.cs:83-87）は保留のままで、信頼を戻す決着（TimecodeSyncService.cs:582-597）に届かない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "着地の冷却中（TimecodeSyncSeekState.cs:83-87）は保留のままで、信頼を戻す決着（TimecodeSyncService.cs:582-597）に届かない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── SingleModeSyncCoordinator.clipBoundaryHeld ──
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.FileLoad, Clears, Clear,
            "v0.5.4 K5 で直した（根拠: LtcSyncController.cs:125 の FileLoad から SingleModeSyncCoordinator.cs:146 の OnLifecycle へ渡し、:167 の ReleaseBoundaryHoldOnFileLoad が解除と同じ経路（SetEndHold(false) + OnBoundaryHoldReleased）を通る。§6 の 1。番号で無効にするだけでは解除の副作用を落とす）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 1: 下ろすのは SingleModeSyncCoordinator.cs:230-240 の解除（LTC が範囲内へ戻る :169-177 か端を離れる :192-193）だけで、このできごとは Single のコーディネーターに通知しない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:153 の SyncModeChanged から呼ぶ。SetEndHold は呼ばない）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:138 の SyncEnabledChanged（無効化）から呼ぶ。SetEndHold は呼ばない）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化（SyncEnabledChanged）でホールドを消す（v0.5.3 段 3c。LtcSyncController.cs:138）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.StopPlayback, Clears, Clear,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:343 の PlaybackStopped から呼ぶ。SetEndHold は呼ばない）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.GapEnter, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── SingleModeSyncCoordinator.boundarySeekTarget ──
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.FileLoad, Clears, Clear,
            "TimecodeSyncService.cs:432 で読み込み番号が進み、SingleModeSyncCoordinator.cs:212-214 の記録は無効になる（v0.5.1）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.FileLoadWithoutBegin, Clears, Clear,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad が読み込み番号を進める）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SyncModeChanged, Clears, Undecided,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:153 の SyncModeChanged から呼び、端へのシークの記録も消す）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SyncEnabledOff, Clears, Undecided,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:138 の SyncEnabledChanged（無効化）から呼び、端へのシークの記録も消す）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化（SyncEnabledChanged）で端へのシークの記録を消す（v0.5.3 段 3c。LtcSyncController.cs:138）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.StopPlayback, Clears, Undecided,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:343 の PlaybackStopped から呼び、端へのシークの記録も消す）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.GapEnter, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSignalLossPolicy.lost ──
        new(LatchArrangements.Lost, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.Lost, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88 監視の停止で初期化する"),
        new(LatchArrangements.Lost, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で初期化する（LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88）"),
        new(LatchArrangements.Lost, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.Lost, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 ギャップへ入る有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.Lost, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 前提と合わせて有効フレーム 2 枚で、復帰の 3 枚に足りない"),
        new(LatchArrangements.Lost, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSignalLossPolicy.cs:112-127 有効フレーム 3 枚で復帰（:122）"),
        new(LatchArrangements.Lost, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSignalLossPolicy.cs:161-194 保持の直後の Jump 1 枚で即復帰（:182）"),
        new(LatchArrangements.Lost, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.Lost, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.Lost, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.Lost, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSignalLossPolicy.pausedByPolicy ──
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88 監視の停止で初期化する"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で初期化する（LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.GapEnter, Keeps, Undecided,
            "停止モードの損失中は同期を抑止し（LtcSyncController.cs:1127）、有効フレーム 1 枚は復帰の 3 枚に足りない（LtcSignalLossPolicy.cs:112）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: 停止モードの損失で一時停止中は同期を抑止し（LtcSyncController.cs:1127）、ギャップへ入れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSignalLossPolicy.cs:112-127 有効フレーム 3 枚で復帰（:127）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSignalLossPolicy.cs:161-194 保持の直後の Jump 1 枚で即復帰（:189）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SignalLossModeChanged, Clears, Clear,
            "利用者決定 2026-09-25（§7）: v0.5.3 で直す。v0.5.3 段 3i で下ろすようにした（LtcSignalLossPolicy.OnSignalLossModeChanged がランスルーへの変更で _pausedByPolicy を下ろす。LtcSignalLossPolicy.cs:100）"),

        // ── LtcSignalLossPolicy.manualResumeSuppressesPause ──
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88 監視の停止で初期化する"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で初期化する（LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない（下ろすのは復帰 :125・:187 と初期化 :86）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 前提と合わせて有効フレーム 2 枚で、復帰の 3 枚に足りない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSignalLossPolicy.cs:112-127 有効フレーム 3 枚で復帰（:125）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSignalLossPolicy.cs:161-194 保持の直後の Jump 1 枚で即復帰（:187）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncSeekState.pendingSeek ──
        new(LatchArrangements.PendingSeek, LifecycleEvent.FileLoad, Keeps, Undecided,
            "v0.5.4 段 B3: BeginFileLoad が読み込みの世代の着地待ちに入る（TimecodeSyncService.cs: BeginFileLoad → BeginLoadWait。前の保留は捨て、読み込みの着地まで位置を使わない）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad がシークの保留を捨てる）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:196 → TimecodeSyncService.cs:497 → TimecodeSyncSeekState.cs:52-59 保留を捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:176 → TimecodeSyncService.cs:497 → TimecodeSyncSeekState.cs:52-59 保留を捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で保留を捨てる（LtcSyncController.cs:176 → TimecodeSyncService.cs:497）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 は保留シークに触れない。シークバーは ClearSeekState を呼ばない（MainWindow.xaml.cs:1977, :2642。呼ぶのはタイムラインのシーク :1966-1967）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は保留シークに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:49-58 同じトラックへのギャップ明けはプレイヤーへ直接シークし（:51）、保留シークに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "TimecodeSyncSeekState.cs:83-87 前提の Tick は時計を進めず、復帰の 3 フレーム（時計で 120ms）は冷却 200ms の内"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "保留を下ろす経路（着地 TimecodeSyncSeekState.cs:78-96・時間切れ :110-115・Clear）のどれにも届かない（時計は進めていない）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "TimecodeSyncSeekState.cs:78-87 目標に着いても 200ms の冷却中は保留のまま"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

    ];
}
