namespace TimecodeSyncPlayer.Tests.LatchLifetime;

/// <summary>
/// v0.5.2 段 0: ラッチの寿命の表（特性テストのデータ）。行 = ラッチ × できごと。
/// 現状 = 今のコードでできごとの直後にラッチが立っているか（テストで確かめる）。
/// 意図 = 設計書 §6 の候補の行は Clear（現状と食い違う行が §6 の候補そのもの）、できごとのコードが
/// 明示的に消している行は Clear（現状と同じ向き）、それ以外は Undecided。
/// 根拠の行番号は v0.5.2 段 0 の時点のファイル。人間向けの写しは docs/design/v0.5.2-latch-table.md。
/// 段 1・2 の間はこの表を変えない（段 3 で §6 の候補を直すとき、その行の現状の列だけを書き換える）。
/// </summary>
public static class LatchLifetimeTable
{
    private const CurrentBehavior Clears = CurrentBehavior.Clears;
    private const CurrentBehavior Keeps = CurrentBehavior.Keeps;
    private const CurrentBehavior NotApplicable = CurrentBehavior.NotApplicable;
    private const LatchIntent Clear = LatchIntent.Clear;
    private const LatchIntent Keep = LatchIntent.Keep;
    private const LatchIntent Undecided = LatchIntent.Undecided;

    public static IReadOnlyList<LatchLifetimeRow> Rows { get; } =
    [
        // ── LtcSyncController.jumpAppliedOnce ──
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.FileLoad, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（TimecodeSyncService.BeginFileLoad の FileLoad を LifecycleRaised で受け、LtcSyncController が 2 つのラッチを下ろす。TimecodeSyncService.cs:68）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 5: v0.5.3 では直さない（ギャップの読み込みは Jump の適用の途中で起きる（GapEnterCoordinator.cs:213・:256）。設計 `v0.5.3-gap-load-entry.md` の親の承認）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の SyncModeChanged で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.SyncEnabledOn, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の SyncEnabled で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:386, :421 監視の停止で下ろす"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:386, :421）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.ManualSeek, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の ManualSeek（と TimelineSeek）で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:581 ギャップへ入るフレームは Normal で、値が進むフレームとして下ろす"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入る Normal フレームで下ろす（LtcSyncController.cs:581）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:581 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:531 で下ろした直後に :536 で立て直す（復帰した Jump を 1 回適用する）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:581 Normal フレームで下ろす（:97-100 のコメント: Normal/Initial で解除）"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.JumpAppliedOnce, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.heldReapplyDone ──
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.FileLoad, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（TimecodeSyncService.BeginFileLoad の FileLoad を LifecycleRaised で受け、LtcSyncController が 2 つのラッチを下ろす。TimecodeSyncService.cs:68）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 5: v0.5.3 では直さない（ギャップの読み込みは Jump の適用の途中で起きる（GapEnterCoordinator.cs:213・:256）。設計 `v0.5.3-gap-load-entry.md` の親の承認）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の SyncModeChanged で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SyncEnabledOn, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の SyncEnabled で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:387, :422 監視の停止で下ろす"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:387, :422）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.ManualSeek, Clears, Clear,
            "v0.5.3 段 3e で下ろすようにした（LtcSyncController.OnLifecycle の ManualSeek（と TimelineSeek）で 2 つのラッチを下ろす。LtcSyncController.cs:199）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:582 ギャップへ入るフレームは Normal で、値が進むフレームとして下ろす"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入る Normal フレームで下ろす（LtcSyncController.cs:582）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:582 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:508-545 Jump の経路はこのラッチに触れない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:582 Normal フレームで下ろす（:97-100 のコメント: Normal/Initial で解除）"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.HeldReapplyDone, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.pendingJump ──
        new(LatchArrangements.PendingJump, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:194 モード切替で未確認の Jump を捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は未確認の Jump に触れない（捨てるのは :194・:257・:372・:384・:419・:458）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は未確認の Jump に触れない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:384, :419 監視の停止で捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で捨てる（LtcSyncController.cs:384, :419）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.ManualSeek, Clears, Clear,
            "LtcSyncController.cs:257 CancelPendingSync が捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:456-458 次のフレームで必ず下ろす（確認できなければ捨てる）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで下ろす（LtcSyncController.cs:458）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:458 前提の無音の後の最初の有効フレームで下ろす"),
        new(LatchArrangements.PendingJump, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: 前提の保持フレームで下ろす（LtcSyncController.cs:458）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:458 次のフレームで下ろす（+1 フレームでないので確認にならず捨てる :462-479）"),
        new(LatchArrangements.PendingJump, LifecycleEvent.FpsModeChanged, Clears, Clear,
            "LtcSyncController.cs:372 fps モードの変更で捨てる"),
        new(LatchArrangements.PendingJump, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PendingJump, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.pendingSync ──
        new(LatchArrangements.PendingSync, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.PendingSync, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:199 の再適用が :213 で下ろし、再適用の同期要求は Complete（:325）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:186 の再適用が :213 で下ろし、同期無効で :216 で戻る"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で下ろす（LtcSyncController.cs:186 → :213）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:383, :418 監視の停止で下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:383, :418）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.ManualSeek, Clears, Clear,
            "LtcSyncController.cs:256 CancelPendingSync が下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset は保留の同期要求に触れない（下ろすのは :213・:256・:325・:383・:418・:947）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:947 有効フレームで下ろし、ギャップの同期要求は Complete（:1199 → :325）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで下ろす（LtcSyncController.cs:947）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SignalRecovered, NotApplicable, Undecided,
            "前提で消える: 前提の無音の Tick が保留を再送し（LtcSyncController.cs:956-963）、Complete で :325 が下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: 前提の Tick が保留を再送し（LtcSyncController.cs:956-963）、Complete で :325 が下ろす"),
        new(LatchArrangements.PendingSync, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:947 有効フレームで下ろし、同期要求は Complete（:325）"),
        new(LatchArrangements.PendingSync, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PendingSync, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PendingSync, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.lastHeldEffective ──
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:381, :416 監視の停止で下ろす"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:381, :416）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:584 ギャップへ入るフレームは Normal で、保持が明けたとして下ろす"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入る Normal フレームで下ろす（LtcSyncController.cs:584）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:584 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.JumpRecovery, Keeps, Clear,
            "§6 の 4: 損失中の Jump の即時復帰（LtcSyncController.cs:527-539）は下ろさない（下ろすのは :584・:633 と監視の停止）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:584 値が進むフレームで下ろす（:89-94 のコメント）"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LastHeldEffective, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.heldLossLanding ──
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:382, :417 監視の停止で下ろす"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:382, :417）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:585 ギャップへ入るフレームは Normal で、保持が明けたとして下ろす"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: 停止モードの損失で一時停止中は同期を抑止し（LtcSyncController.cs:1127）、ギャップへ入れない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:585 復帰の有効フレーム（Normal）で下ろす"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.JumpRecovery, Keeps, Clear,
            "§6 の 4: 損失中の Jump の即時復帰（LtcSyncController.cs:527-539）は下ろさない（下ろすのは :585・:646・:1114 と監視の停止）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:585 値が進むフレームで下ろす（:89-94 のコメント）"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.HeldLossLanding, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.lastAppliedLtc ──
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:380, :415 監視の停止で下ろす"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:380, :415）"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:600 復帰した Jump の値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:600 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LastAppliedLtc, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.lastAcceptedLtc ──
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（無効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged（有効化）はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:379, :414 監視の停止で下ろす"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:379, :414）"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:597 復帰した Jump の値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:597 有効フレームで新しい値に立て直す"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LastAcceptedLtc, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.followStartPending ──
        new(LatchArrangements.FollowStartPending, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 は触れない。再適用（:199）は受理値が無く（監視の開始 :379 で消えている）:215 で戻るので消費しない"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:177 同期の無効化で下ろす"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で下ろす（LtcSyncController.cs:177）"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:401, :423 監視の停止で下ろす"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で下ろす（LtcSyncController.cs:401, :423）"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.GapEnter, Clears, Undecided,
            "LtcSyncController.cs:1132-1134 最初の同期評価で消費する（ギャップの分岐より前）"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで消費する（LtcSyncController.cs:1132-1134）"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.SignalRecovered, NotApplicable, Undecided,
            "前提を作れない: 立てた監視の開始で信号断の検出が初期化され（LtcSyncController.cs:391）、有効フレームが無いと損失にならない（LtcSignalLossPolicy.cs:223-225）。有効フレームを送ると :1132-1134 で消費する"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提を作れない: 立てた監視の開始で信号断の検出が初期化され（LtcSyncController.cs:391）、有効フレームが無いと損失にならない（LtcSignalLossPolicy.cs:223-225）。有効フレームを送ると :1132-1134 で消費する"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.NormalFrame, Clears, Undecided,
            "LtcSyncController.cs:1132-1134 最初の同期評価で消費する"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.FollowStartPending, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.rateRestorePending ──
        new(LatchArrangements.RateRestorePending, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:191 の ResetCorrection は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SyncEnabledOff, Keeps, Clear,
            "§6 の 7: ResetCorrection（LtcSyncController.cs:172）は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:172 の ResetCorrection は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:260 の ResetCorrection は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset は復帰待ちのとき何もしない（:292）"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1176 の ResetCorrection は :292 で何もしない。ギャップで一時停止し、復帰（:784-791）は :776 で届かない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.GapExit, Clears, Clear,
            "LtcSyncController.cs:784-791 再生が戻ったフレームの補正評価で 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:784-791 補正評価の前に 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSyncController.cs:610 → :784-791 補正評価の前に 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:615 → :784-791 補正評価の前に 1.0 に戻して下ろす"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.RateRestorePending, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.smoothUnavailable ──
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.FileLoad, Keeps, Clear,
            "§6 の 6: 戻すのは LtcSyncController.cs:173・:192・:1166（Continue のトラック切替）だけで、Single の読み込みは通らない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 6: v0.5.3 では直さない（ギャップの読み込みは Jump の適用の途中で起きる（GapEnterCoordinator.cs:213・:256）。設計 `v0.5.3-gap-load-entry.md` の親の承認）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:192 モード切替で Smooth を再試行できるようにする"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:173 同期の切替で Smooth を再試行できるようにする"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で下ろす（LtcSyncController.cs:173）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.ManualSeek, Clears, Clear,
            "利用者決定 2026-09-25（§7）: v0.5.3 で直す。v0.5.3 段 3h で下ろすようにした（LtcSyncController.OnLifecycle の ManualSeek（と TimelineSeek）で _rate.ResetSmoothAvailability を呼ぶ。LtcSyncController.cs:237）"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 → :286-298 ResetCorrection は :81 の _smoothAvailable を戻さない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:1166 はトラック切替のときだけで、このフレームは切替ではない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.SmoothUnavailable, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.correctionPausedForPosition ──
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.FileLoad, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす。再適用（:199）の同期要求は補正評価（ApplyCorrection）を呼ばない（:300-332）"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす。再適用（:186）の同期要求は補正評価（ApplyCorrection）を呼ばない（:300-332）"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす（ResetCorrection :286-298 も触れない）。このできごとは補正評価を通らない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:809-811 だけが下ろす。ギャップで一時停止し、補正評価は :776 で戻って届かない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.GapExit, Clears, Clear,
            "LtcSyncController.cs:615 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSyncController.cs:615 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSyncController.cs:610 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.NormalFrame, Clears, Clear,
            "LtcSyncController.cs:615 → :809-811 位置が安定したフレームの補正評価で下ろす"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.CorrectionPausedForPosition, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSyncController.rateNotUnity ──
        new(LatchArrangements.RateNotUnity, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は TimecodeSyncService の中だけを初期化し、LtcSyncController.cs には通知しない"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:191 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:172 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で 1.0 に戻す（LtcSyncController.cs:172 → :294-295）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-433 監視の停止は補正状態（倍率）に触れない"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:377-404 監視の開始は補正状態（倍率）に触れない"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.ManualSeek, Clears, Clear,
            "LtcSyncController.cs:260 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.StopPlayback, Clears, Clear,
            "MainWindow.xaml.cs:1536 → LtcSyncController.cs:280 → :294-295 倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.GapEnter, Clears, Clear,
            "LtcSyncController.cs:1176 → :294-295 ギャップでは倍率を 1.0 に戻す"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提で消える: 前提のギャップへ入るフレームで 1.0 に戻す（LtcSyncController.cs:1176）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "LtcSyncController.cs:859-878 補正評価は残差（0.2 秒）に応じて Smooth の倍率を掛け続ける"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:859-878 補正評価は残差（0.2 秒）に応じて Smooth の倍率を掛け続ける"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSyncController.cs:859-878 補正評価は残差（0.2 秒）に応じて Smooth の倍率を掛け続ける"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.CorrectionModeChanged, Clears, Clear,
            "v0.5.3 段 3h で下ろすようにした（LtcSyncController.OnLifecycle の CorrectionModeChanged で ResetCorrection を呼ぶ。LtcSyncController.cs:242）"),
        new(LatchArrangements.RateNotUnity, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.loadingFile ──
        new(LatchArrangements.LoadingFile, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:433 読み込みで立て直す"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:196 の ClearSeekState（TimecodeSyncService.cs:495-503）はロード中に触れず、再適用の評価でも再生・描画が進まず解除条件（:466-470）に届かない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "v0.5.3 段 3d で取り消すようにした（TimecodeSyncService.OnLifecycle の SyncDisabled でロード中の印と解除の回収待ちを下ろす。解除はしない（着地窓を開かない）。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で取り消す（v0.5.3 段 3d。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.StopPlayback, Clears, Clear,
            "v0.5.3 段 3d で取り消すようにした（LtcSyncController.PlaybackStopped から _syncService.OnLifecycle(PlaybackStopped) を呼ぶ。解除はしない。LtcSyncController.cs:343）"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は読み込みの解除（TimecodeSyncService.cs:457-479）を通らない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:49-58 同じトラックへのギャップ明けは読み込まず、解除の判定（:119）も通らない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SignalRecovered, Clears, Undecided,
            "信号の復帰そのものではなく、有効フレーム 3 枚で再生 0.12 秒・描画 3 枚が進み、TimecodeSyncService.cs:466-478 の解除条件（0.08 秒・2 枚）を満たす"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "前提の保持と Jump の評価でも再生・描画が進まず、TimecodeSyncService.cs:466-476 の解除条件に届かない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "再生 0.04 秒・描画 1 枚では TimecodeSyncService.cs:466-470 の解除条件（0.08 秒・2 枚）に届かない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.LoadingFile, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.fileLoadReleasePending ──
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.FileLoad, Clears, Clear,
            "TimecodeSyncService.cs:434 読み込みで下ろす"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.FileLoadWithoutBegin, Clears, Clear,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad が解除の回収待ちを下ろす）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SyncEnabledOff, Clears, Undecided,
            "v0.5.3 段 3d で取り消すようにした（TimecodeSyncService.OnLifecycle の SyncDisabled で解除の回収待ちも下ろす。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で取り消す（v0.5.3 段 3d。TimecodeSyncService.cs:306）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.StopPlayback, Clears, Undecided,
            "v0.5.3 段 3d で取り消すようにした（LtcSyncController.PlaybackStopped から _syncService.OnLifecycle(PlaybackStopped) を呼び、解除の回収待ちも下ろす。LtcSyncController.cs:343）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.GapEnter, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.GapExit, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.JumpRecovery, NotApplicable, Undecided,
            "前提で消える: 前提の保持フレーム（LtcSyncController.cs:573-576 → :738-763）が PollFileLoadRelease で回収して下ろす（TimecodeSyncService.cs:520-523）"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "下ろすのは保持フレームの回収（TimecodeSyncService.cs:511-535）と読み込み（:434）だけで、このできごとは回収を通らない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.FileLoadReleasePending, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.seekLandingActive ──
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:451 読み込みで窓を開き直す"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.SyncModeChanged, Clears, Undecided,
            "LtcSyncController.cs:196 で位置を信頼し直し（TimecodeSyncService.cs:501）、:199 の再適用の同期評価が許容内で着地を閉じる（TimecodeSyncService.cs:151-152 → :319-328）"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:176 の ClearSeekState（TimecodeSyncService.cs:495-503）は着地の窓に触れず、再適用は同期無効で :216 で戻る"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.SyncEnabledOn, Clears, Undecided,
            "LtcSyncController.cs:183 で追従開始を立て、:186 の再適用が :1135 で窓を開き直した後、同期評価が許容内で閉じる（TimecodeSyncService.cs:151-152 → :319-328）"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は同期評価（EvaluateDecision）も読み込みの解除も通らない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:54 ギャップ明けで窓を開き直す"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "着地の冷却中は位置を信頼せず同期評価が TimecodeSyncService.cs:121-127 で戻るので、到着（:151-152）を観測しない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "LtcSyncController.cs:608 → TimecodeSyncService.cs:278-284 は発生元だけを変え、窓は残す"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "着地の冷却中は位置を信頼せず同期評価が TimecodeSyncService.cs:121-127 で戻るので、到着（:151-152）を観測しない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.SeekLandingActive, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.followStartLanding ──
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:451 → :238-240, :246-247 開き直しても追従開始の発生元を保つ"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.SyncModeChanged, Clears, Undecided,
            "LtcSyncController.cs:196 で位置を信頼し直し（TimecodeSyncService.cs:501）、:199 の再適用の同期評価が許容内で着地を閉じる（TimecodeSyncService.cs:151-152 → :319-328）"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:176 の ClearSeekState（TimecodeSyncService.cs:495-503）は着地の窓に触れず、再適用は同期無効で :216 で戻る"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.SyncEnabledOn, Clears, Undecided,
            "LtcSyncController.cs:183 で追従開始を立て、:186 の再適用が :1135 で窓を開き直した後、同期評価が許容内で閉じる（TimecodeSyncService.cs:151-152 → :319-328）"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は同期評価（EvaluateDecision）も読み込みの解除も通らない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:54 NotifyLanding(Other) でも追従開始の発生元を保つ（TimecodeSyncService.cs:238-240）"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "着地の冷却中は位置を信頼せず同期評価が TimecodeSyncService.cs:121-127 で戻るので、到着（:151-152）を観測しない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSyncController.cs:608 → TimecodeSyncService.cs:278-284 LTC の Jump で追従開始のエピソードを終える"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "着地の冷却中は位置を信頼せず同期評価が TimecodeSyncService.cs:121-127 で戻るので、到着（:151-152）を観測しない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.FollowStartLanding, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncService.positionUntrusted ──
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.FileLoad, Clears, Clear,
            "TimecodeSyncService.cs:446 読み込みで位置の信頼を初期化する"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 2: PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginFileLoad（TimecodeSyncService.cs:446）を通らない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:196 → TimecodeSyncService.cs:501 保留を捨てて位置を使い直す"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:176 → TimecodeSyncService.cs:501 保留を捨てて位置を使い直す"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で信頼し直す（LtcSyncController.cs:176 → TimecodeSyncService.cs:501）"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 は TimecodeSyncService に触れない。シークバーは ClearSeekState を呼ばない（MainWindow.xaml.cs:1977, :2642。呼ぶのはタイムラインのシーク :1966-1967）"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は同期評価（EvaluateDecision）も読み込みの解除も通らない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:51 ギャップ明けのシークはプレイヤーへ直接出し、保留の決着（TimecodeSyncService.cs:582-597）を通らない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "着地の冷却中（TimecodeSyncSeekState.cs:83-87）は保留のままで、信頼を戻す決着（TimecodeSyncService.cs:582-597）に届かない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "着地の冷却中（TimecodeSyncSeekState.cs:83-87）は保留のままで、信頼を戻す決着（TimecodeSyncService.cs:582-597）に届かない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "着地の冷却中（TimecodeSyncSeekState.cs:83-87）は保留のままで、信頼を戻す決着（TimecodeSyncService.cs:582-597）に届かない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PositionUntrusted, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── SingleModeSyncCoordinator.clipBoundaryHeld ──
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.FileLoad, Keeps, Clear,
            "§6 の 1: v0.5.3 では直さない: 読み込みの後の最初の評価で解除（再開と片付け）が起きる（SingleModeSyncCoordinator.cs:248 の ReleaseBoundaryHold）。番号で無効にすると解除が起きず、GPU 復旧の後に止まったままになる（段 3c の手直し）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.FileLoadWithoutBegin, Keeps, Clear,
            "§6 の 1: 下ろすのは SingleModeSyncCoordinator.cs:230-240 の解除（LTC が範囲内へ戻る :169-177 か端を離れる :192-193）だけで、このできごとは Single のコーディネーターに通知しない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:153 の SyncModeChanged から呼ぶ。SetEndHold は呼ばない）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:138 の SyncEnabledChanged（無効化）から呼ぶ。SetEndHold は呼ばない）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化（SyncEnabledChanged）でホールドを消す（v0.5.3 段 3c。LtcSyncController.cs:138）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.StopPlayback, Clears, Clear,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:343 の PlaybackStopped から呼ぶ。SetEndHold は呼ばない）"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.GapEnter, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.ClipBoundaryHeld, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── SingleModeSyncCoordinator.boundarySeekTarget ──
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.FileLoad, Clears, Clear,
            "TimecodeSyncService.cs:432 で読み込み番号が進み、SingleModeSyncCoordinator.cs:212-214 の記録は無効になる（v0.5.1）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.FileLoadWithoutBegin, Clears, Clear,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad が読み込み番号を進める）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SyncModeChanged, Clears, Undecided,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:153 の SyncModeChanged から呼び、端へのシークの記録も消す）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SyncEnabledOff, Clears, Undecided,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:138 の SyncEnabledChanged（無効化）から呼び、端へのシークの記録も消す）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化（SyncEnabledChanged）で端へのシークの記録を消す（v0.5.3 段 3c。LtcSyncController.cs:138）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.StopPlayback, Clears, Undecided,
            "v0.5.3 段 3c で消すようにした（SingleModeSyncCoordinator.OnLifecycle を LtcSyncController.cs:343 の PlaybackStopped から呼び、端へのシークの記録も消す）"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.GapEnter, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: ギャップは Continue にしか無く、このラッチは Single でしか立たない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "フレームの LTC は範囲外のまま（SingleModeSyncCoordinator.cs:160-161）。下ろすのは範囲内へ戻る（:164, :169-177）か端を離れる（:188-194）ときだけ"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.BoundarySeekTarget, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSignalLossPolicy.lost ──
        new(LatchArrangements.Lost, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.Lost, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88 監視の停止で初期化する"),
        new(LatchArrangements.Lost, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で初期化する（LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88）"),
        new(LatchArrangements.Lost, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.Lost, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.Lost, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 ギャップへ入る有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.Lost, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 前提と合わせて有効フレーム 2 枚で、復帰の 3 枚に足りない"),
        new(LatchArrangements.Lost, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSignalLossPolicy.cs:112-127 有効フレーム 3 枚で復帰（:122）"),
        new(LatchArrangements.Lost, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSignalLossPolicy.cs:161-194 保持の直後の Jump 1 枚で即復帰（:182）"),
        new(LatchArrangements.Lost, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.Lost, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.Lost, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.Lost, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── LtcSignalLossPolicy.pausedByPolicy ──
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88 監視の停止で初期化する"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で初期化する（LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.GapEnter, Keeps, Undecided,
            "停止モードの損失中は同期を抑止し（LtcSyncController.cs:1127）、有効フレーム 1 枚は復帰の 3 枚に足りない（LtcSignalLossPolicy.cs:112）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.GapExit, NotApplicable, Undecided,
            "前提を作れない: 停止モードの損失で一時停止中は同期を抑止し（LtcSyncController.cs:1127）、ギャップへ入れない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSignalLossPolicy.cs:112-127 有効フレーム 3 枚で復帰（:127）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSignalLossPolicy.cs:161-194 保持の直後の Jump 1 枚で即復帰（:189）"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PausedByPolicy, LifecycleEvent.SignalLossModeChanged, Keeps, Clear,
            "§6 の 9: MainWindow.xaml.cs:484-490 は保存とログだけ。ポリシーはモードを一時停止の判断（LtcSignalLossPolicy.cs:243-257）でしか見ず、止めたまま復帰を待つ"),

        // ── LtcSignalLossPolicy.manualResumeSuppressesPause ──
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.FileLoad, Keeps, Undecided,
            "TimecodeSyncService.cs:429-452 BeginFileLoad は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.FileLoadWithoutBegin, Keeps, Undecided,
            "PlaybackOperationsCoordinator.cs:82-83 位置つきの読み込みは BeginSyncFileLoad を呼ばず、同期側の入口は何も呼ばれない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:189-200 SyncModeChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "LtcSyncController.cs:170-187 SyncEnabledChanged は信号断のポリシーに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.MonitoringStopped, Clears, Clear,
            "LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88 監視の停止で初期化する"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.MonitoringStarted, NotApplicable, Undecided,
            "前提で消える: 前提の監視の停止で初期化する（LtcSyncController.cs:399, :426 → LtcSignalLossPolicy.cs:79-88）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 CancelPendingSync はこのラッチに触れない（シークバーはプレイヤーへ直接シークする）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない（下ろすのは復帰 :125・:187 と初期化 :86）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.GapExit, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 前提と合わせて有効フレーム 2 枚で、復帰の 3 枚に足りない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SignalRecovered, Clears, Clear,
            "LtcSignalLossPolicy.cs:112-127 有効フレーム 3 枚で復帰（:125）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.JumpRecovery, Clears, Clear,
            "LtcSignalLossPolicy.cs:161-194 保持の直後の Jump 1 枚で即復帰（:187）"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "LtcSignalLossPolicy.cs:112 有効フレーム 1 枚は復帰の 3 枚に足りない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.ManualResumeSuppressesPause, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncSeekState.pendingSeek ──
        new(LatchArrangements.PendingSeek, LifecycleEvent.FileLoad, Clears, Clear,
            "TimecodeSyncService.cs:440 → TimecodeSyncSeekState.cs:52-59 読み込みで保留を捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.FileLoadWithoutBegin, Clears, Clear,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad がシークの保留を捨てる）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SyncModeChanged, Clears, Clear,
            "LtcSyncController.cs:196 → TimecodeSyncService.cs:497 → TimecodeSyncSeekState.cs:52-59 保留を捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SyncEnabledOff, Clears, Clear,
            "LtcSyncController.cs:176 → TimecodeSyncService.cs:497 → TimecodeSyncSeekState.cs:52-59 保留を捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SyncEnabledOn, NotApplicable, Undecided,
            "前提で消える: 前提の同期の無効化で保留を捨てる（LtcSyncController.cs:176 → TimecodeSyncService.cs:497）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "LtcSyncController.cs:377-404 MonitoringChanged と :412-433 MonitorStopped はこのラッチに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "LtcSyncController.cs:388-396 MonitoringChanged（開始）はこのラッチに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "LtcSyncController.cs:254-261 は保留シークに触れない。シークバーは ClearSeekState を呼ばない（MainWindow.xaml.cs:1977, :2642。呼ぶのはタイムラインのシーク :1966-1967）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "LtcSyncController.cs:280 CorrectionReset（:286-298）はこのラッチに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.GapEnter, Keeps, Undecided,
            "LtcSyncController.cs:1174-1191 ギャップの分岐は保留シークに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.GapExit, Keeps, Undecided,
            "ContinueOnTrackCoordinator.cs:49-58 同じトラックへのギャップ明けはプレイヤーへ直接シークし（:51）、保留シークに触れない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "TimecodeSyncSeekState.cs:83-87 前提の Tick は時計を進めず、復帰の 3 フレーム（時計で 120ms）は冷却 200ms の内"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "保留を下ろす経路（着地 TimecodeSyncSeekState.cs:78-96・時間切れ :110-115・Clear）のどれにも届かない（時計は進めていない）"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "TimecodeSyncSeekState.cs:78-87 目標に着いても 200ms の冷却中は保留のまま"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "LtcSyncController.cs:370-375 FpsModeChanged は未確認の Jump と fps の選択だけを捨てる"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:470-476 設定の保存とログだけで、同期側の入口を呼ばない"),
        new(LatchArrangements.PendingSeek, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "MainWindow.xaml.cs:484-490 設定の保存とログだけで、同期側の入口を呼ばない"),

        // ── TimecodeSyncSeekState.lastSettledRecent ──
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.FileLoad, Clears, Clear,
            "v0.5.3 段 3f で忘れるようにした（TimecodeSyncService.OnLifecycle の FileLoad で _seekState.Clear() の後に ForgetLastSettled() を呼ぶ。TimecodeSyncService.cs:314・TimecodeSyncSeekState.cs:65）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.FileLoadWithoutBegin, Clears, Clear,
            "v0.5.3 段 3g で口を通すようにした（ギャップの読み込みの後（GapEnterCoordinator.cs:213・:256、MainWindow.xaml.cs:2389）に TimecodeSyncService.BeginGapFreezeLoad が直前の着地の記録を忘れる）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.SyncModeChanged, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.SyncEnabledOff, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.SyncEnabledOn, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.MonitoringStopped, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.MonitoringStarted, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.ManualSeek, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.StopPlayback, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.GapEnter, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる（このできごとは時計を 120ms 以内しか進めない）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.GapExit, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる（このできごとは時計を 120ms 以内しか進めない）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.SignalRecovered, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる（このできごとは時計を 120ms 以内しか進めない）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.JumpRecovery, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる（このできごとは時計を 120ms 以内しか進めない）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.NormalFrame, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる（このできごとは時計を 120ms 以内しか進めない）"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.FpsModeChanged, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.CorrectionModeChanged, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
        new(LatchArrangements.LastSettledRecent, LifecycleEvent.SignalLossModeChanged, Keeps, Undecided,
            "着地の記録（TimecodeSyncSeekState.cs:92-93）を消す経路は無く、時間（500ms、:66-72）だけで切れる"),
    ];
}
